## Import data

In [ ]:
import pandas as pd
ATAC = pd.read_csv("data/1.ATAC-Seq data.CSV", sep=";")
RNA = pd.read_csv("data/2.RNA-Seq data.CSV", sep=";")
ATAC_QC = pd.read_csv("data/ATAC_QCmatric.CSV", sep=";")
ATAC_QC_RS = pd.read_csv("data/ATAC_QCmatric_ReadStatistics.CSV", sep=";")

Extraction of B cells and upstream hematopoietic stem and progenitor cells from the datasets

## ATAC-Seq data

In [ ]:
#
ATAC_Bcells = ATAC.iloc[:, :31]
ATAC_Bcells.to_csv("data/ATAC_Bcells.csv", index=False)
ATAC_Bcells.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,LTHSC.34-.BM,LTHSC.34+.BM,...,B.Sp,B.Fem.Sp,B.MZ.Sp,B.Fo.Sp,B.mem.Sp,B.GC.CB.Sp,B.GC.CC.Sp,B.PB.Sp,B.PC.Sp,B.PC.BM
0,ImmGenATAC1219.peak_1,chr1,3020786,0.00,0.56,NaN,NaN,NaN,0.41,0.71,...,0.59,20486.00,0.65,28856.00,0.46,0.12,31079.00,24198.00,20821.00,42125.00
1,ImmGenATAC1219.peak_2,chr1,3087226,0.00,0.50,NaN,NaN,NaN,0.41,23377.00,...,0.59,42064.00,21551.00,0.36,0.70,0.12,0.73,0.75,12816.00,45870.00
2,ImmGenATAC1219.peak_3,chr1,3120109,0.07,45879.00,1.0,NaN,NaN,13181.00,0.10,...,0.59,0.49,45839.00,0.36,1.00,45992.00,0.28,11689.00,0.14,46935.00
3,ImmGenATAC1219.peak_4,chr1,3121485,0.15,45691.00,1.0,NaN,NaN,0.41,0.10,...,0.59,44197.00,0.11,0.70,44927.00,0.71,0.28,0.10,0.14,26359.00
4,ImmGenATAC1219.peak_5,chr1,3372787,0.03,11324.00,NaN,NaN,NaN,0.41,0.10,...,45689.00,0.10,0.11,17533.00,0.12,0.71,44197.00,0.75,45871.00,0.66

## RNA-Seq data

In [18]:
RNA_Bcells = RNA.iloc[:, :23]
RNA_Bcells.to_csv("data/RNA_Bcells.csv", index=False)
RNA_Bcells.head()

,Unnamed: 0,LTHSC.34-.BM,LTHSC.34+.BM,STHSC.150-.BM,MPP4.135+.BM,proB.CLP.BM,proB.FrA.BM,proB.FrBC.BM,B.FrE.BM,B1b.PC,...,B.Sp,B.Fem.Sp,B.MZ.Sp,B.Fo.Sp,B.mem.Sp,B.GC.CB.Sp,B.GC.CC.Sp,B.PB.Sp,B.PC.Sp,B.PC.BM
0,0610005C13Rik,1.096.731.711,1.096.731.711,1.021.750.097,102.181.159,1.205.235.792,1.326.779.959,1.392.995.822,1.821.243.417,1.025.543.402,...,1.024.818.568,1.026.268.237,158.315.998,2.031.567.559,1.023.170.884,1.402.181.757,1.600.162.755,1.024.314.279,102.684.718,1.022.362.769
1,0610007P14Rik,2.060.539.867,2.461.053.168,1.924.246.358,2.042.983.576,1.897.591.745,2.101.951.555,1.802.194.401,1.378.025.433,1.394.367.192,...,1.716.164.054,1.600.865.671,1.955.180.576,1.772.961.633,1.336.412.174,1.597.272.792,2.087.016.962,1.700.951.105,1.685.336.316,2.597.576.315
2,0610009B22Rik,7.827.205.873,7.883.703.048,6.884.475.073,7.641.816.858,1.060.856.192,7.750.281.723,6.821.309.233,572.244.261,5.678.748.898,...,4.111.211.449,3.555.379.368,4.965.223.198,3.440.006.001,2.355.237.438,6.277.779.917,356.740.414,7.266.521.906,1.058.590.211,5.673.230.653
3,0610009L18Rik,857.715.947,1.679.138.572,155.115.492,1.694.735.423,1.058.370.366,8.664.784.443,2.878.171.712,8.952.120.008,1.187.398.402,...,1.262.049.355,9.932.675.127,1.772.575.792,1.486.779.904,1.288.332.862,1.258.651.883,1.049.192.129,1.823.690.155,3.481.405.729,3.253.802.603
4,0610009O20Rik,168.645.852,1.579.260.221,1.559.416.414,1.862.614.637,1.625.845.558,1.520.880.024,1.630.722.909,1.331.160.831,8.805.298.222,...,1.189.817.857,9.724.672.436,1.261.601.665,9.847.900.783,1.032.533.741,9.527.704.619,1.034.410.576,9.217.648.985,1.173.169.177,6.144.418.032

## ATAC_QC data

In [19]:
ATAC_QC_Bcells = ATAC_QC.iloc[:44, :]
ATAC_QC_Bcells.to_csv("data/ATAC_QC_Bcells.csv", index=False)
ATAC_QC_Bcells.head()

,SampleName,CellType,ImmGenLab,Lineage,CellFamily,Organ,SortingMarkers,InputCellNumber,PF.reads,%chrM.mapped,Paired.read.after.removing.PCR.duplication,%fragment.1Kb_TSS,Replicate.cor
0,LTHSC.34-.BM#1,LTHSC.34-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34-,677,22287984,"4,58",2470102,"10,6",NaN
1,LTHSC.34+.BM#1,LTHSC.34+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34+,2483,28588536,"3,17",7675501,"7,7",NaN
2,STHSC.150-.BM#1,STHSC.150-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150-CD48-,3660,22170346,"3,25",6060045,"11,13",NaN
3,MPP4.135+.BM#1,MPP4.135+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135+,10000,24003590,"13,83",6128252,"18,96",NaN
4,proB.CLP.BM#1,proB.CLP.BM,Hardy,B,B Cell,Bone Marrow,CD19-IgM-CD43+CD24-CD45R-CD93+CD117+IL7Ra+PI-D...,10000,23578208,"7,67",6588564,"13,21","0,868"

## ATAC_QC_RS data

In [20]:
ATAC_QC_RS_Bcells = ATAC_QC_RS.iloc[:42, :]
ATAC_QC_RS_Bcells.to_csv("data/ATAC_QC_RS_Bcells.csv", index=False)
ATAC_QC_RS_Bcells.head()

,ImmGen.lab.contributed,sample.name,population.name,total.reads,overal_ alignment_rate%,mapped_MAPQ5,reads.after.removing.duplication,properly_paired.reads,paired.count,total.Htseq-count.on.genes
0,Wagers,LTHSC.34-.BM.rep1,LTHSC.34-.BM,30846074,"56,32",16524909,10069268,9582214,4791107,4641976
1,Wagers,LTHSC.34-.BM.rep2,LTHSC.34-.BM,12221064,"55,26",6432458,4424534,4103998,2051999,1984953
2,Wagers,LTHSC.34+.BM.rep1,LTHSC.34+.BM,18001678,"61,14",10460447,6606793,6263510,3131755,3030056
3,Wagers,LTHSC.34+.BM.rep2,LTHSC.34+.BM,20921592,"61,41",12255655,8074178,7652366,3826183,3709788
4,Wagers,STHSC.150-.BM.rep1,STHSC.150-.BM,26562826,"55,4",14008223,8315375,7899112,3949556,3824397