## Import data

In [2]:
import pandas as pd
ATAC = pd.read_csv("data/converted_ATAC_seq_info.csv", sep=";")
RNA = pd.read_csv("data/converted_ATAC_seq_info.csv", sep=";")
ATAC_QC = pd.read_csv("data/ATAC_QCmatric.CSV", sep=";")
ATAC_QC_RS = pd.read_csv("data/ATAC_QCmatric_ReadStatistics.CSV", sep=";")

Extraction of B cells and upstream hematopoietic stem and progenitor cells from the datasets

## ATAC-Seq data

In [3]:
ATAC_Bcells = ATAC.iloc[:, :31]
ATAC_Bcells.to_csv("data/ATAC_Bcells.csv", index=False)
ATAC_Bcells.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,LTHSC.34-.BM,LTHSC.34+.BM,...,B.Sp,B.Fem.Sp,B.MZ.Sp,B.Fo.Sp,B.mem.Sp,B.GC.CB.Sp,B.GC.CC.Sp,B.PB.Sp,B.PC.Sp,B.PC.BM
0,ImmGenATAC1219.peak_1,chr1,3020786,0.00,0.56,NaN,NaN,NaN,0.41,0.71,...,0.59,2.56,0.65,1.79,0.46,0.12,2.85,4.66,1.57,5.15
1,ImmGenATAC1219.peak_2,chr1,3087226,0.00,0.50,NaN,NaN,NaN,0.41,1.64,...,0.59,3.15,1.59,0.36,0.70,0.12,0.73,0.75,2.35,1.08
2,ImmGenATAC1219.peak_3,chr1,3120109,0.07,10.80,1.0,NaN,NaN,2.36,0.10,...,0.59,0.49,1.70,0.36,1.00,1.12,0.28,1.32,0.14,7.28
3,ImmGenATAC1219.peak_4,chr1,3121485,0.15,3.02,1.0,NaN,NaN,0.41,0.10,...,0.59,1.21,0.11,0.70,1.23,0.71,0.28,0.10,0.14,3.72
4,ImmGenATAC1219.peak_5,chr1,3372787,0.03,1.31,NaN,NaN,NaN,0.41,0.10,...,1.02,0.10,0.11,1.48,0.12,0.71,1.21,0.75,2.08,0.66

## RNA-Seq data

In [4]:
RNA_Bcells = RNA.iloc[:, :23]
RNA_Bcells.to_csv("data/RNA_Bcells.csv", index=False)
RNA_Bcells.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,LTHSC.34-.BM,LTHSC.34+.BM,...,proB.FrA.BM,proB.FrBC.BM,preB.FrD.BM,B.FrE.BM,B1b.PC,B.T1.Sp,B.T2.Sp,B.T3.Sp,B.Sp,B.Fem.Sp
0,ImmGenATAC1219.peak_1,chr1,3020786,0.00,0.56,NaN,NaN,NaN,0.41,0.71,...,0.10,0.11,1.69,0.57,0.14,0.50,0.71,0.57,0.59,2.56
1,ImmGenATAC1219.peak_2,chr1,3087226,0.00,0.50,NaN,NaN,NaN,0.41,1.64,...,0.34,0.82,0.13,0.11,0.93,0.11,0.44,0.32,0.59,3.15
2,ImmGenATAC1219.peak_3,chr1,3120109,0.07,10.80,1.0,NaN,NaN,2.36,0.10,...,0.10,0.50,1.17,0.32,0.14,0.11,1.21,0.57,0.59,0.49
3,ImmGenATAC1219.peak_4,chr1,3121485,0.15,3.02,1.0,NaN,NaN,0.41,0.10,...,0.40,0.50,2.23,0.80,0.14,1.61,0.37,0.36,0.59,1.21
4,ImmGenATAC1219.peak_5,chr1,3372787,0.03,1.31,NaN,NaN,NaN,0.41,0.10,...,0.34,1.78,1.17,0.32,0.60,0.51,1.03,0.10,1.02,0.10

## ATAC_QC data

In [5]:
ATAC_QC_Bcells = ATAC_QC.iloc[:44, :]
ATAC_QC_Bcells.to_csv("data/ATAC_QC_Bcells.csv", index=False)
ATAC_QC_Bcells.head()

,SampleName,CellType,ImmGenLab,Lineage,CellFamily,Organ,SortingMarkers,InputCellNumber,PF.reads,%chrM.mapped,Paired.read.after.removing.PCR.duplication,%fragment.1Kb_TSS,Replicate.cor
0,LTHSC.34-.BM#1,LTHSC.34-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34-,677,22287984,"4,58",2470102,"10,6",NaN
1,LTHSC.34+.BM#1,LTHSC.34+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34+,2483,28588536,"3,17",7675501,"7,7",NaN
2,STHSC.150-.BM#1,STHSC.150-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150-CD48-,3660,22170346,"3,25",6060045,"11,13",NaN
3,MPP4.135+.BM#1,MPP4.135+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135+,10000,24003590,"13,83",6128252,"18,96",NaN
4,proB.CLP.BM#1,proB.CLP.BM,Hardy,B,B Cell,Bone Marrow,CD19-IgM-CD43+CD24-CD45R-CD93+CD117+IL7Ra+PI-D...,10000,23578208,"7,67",6588564,"13,21","0,868"

## ATAC_QC_RS data

In [6]:
ATAC_QC_RS_Bcells = ATAC_QC_RS.iloc[:42, :]
ATAC_QC_RS_Bcells.to_csv("data/ATAC_QC_RS_Bcells.csv", index=False)
ATAC_QC_RS_Bcells.head()

,ImmGen.lab.contributed,sample.name,population.name,total.reads,overal_ alignment_rate%,mapped_MAPQ5,reads.after.removing.duplication,properly_paired.reads,paired.count,total.Htseq-count.on.genes
0,Wagers,LTHSC.34-.BM.rep1,LTHSC.34-.BM,30846074,"56,32",16524909,10069268,9582214,4791107,4641976
1,Wagers,LTHSC.34-.BM.rep2,LTHSC.34-.BM,12221064,"55,26",6432458,4424534,4103998,2051999,1984953
2,Wagers,LTHSC.34+.BM.rep1,LTHSC.34+.BM,18001678,"61,14",10460447,6606793,6263510,3131755,3030056
3,Wagers,LTHSC.34+.BM.rep2,LTHSC.34+.BM,20921592,"61,41",12255655,8074178,7652366,3826183,3709788
4,Wagers,STHSC.150-.BM.rep1,STHSC.150-.BM,26562826,"55,4",14008223,8315375,7899112,3949556,3824397

# ATAC-Seq transponierte Daten

In [7]:
ATAC_Peaks_Bcells = ATAC.iloc[:, 8:31]
ATAC_T_Bcells = ATAC_Peaks_Bcells.T
ATAC_T_Bcells = ATAC_T_Bcells.reset_index()
ATAC_T_Bcells.to_csv("data/ATAC_T_Bcells.csv", index=False)
ATAC_T_Bcells.head()

,index,0,1,2,3,4,5,6,7,8,...,512585,512586,512587,512588,512589,512590,512591,512592,512593,512594
0,LTHSC.34-.BM,0.41,0.41,2.36,0.41,0.41,2.36,0.41,2.36,4.37,...,4.37,0.41,0.41,0.41,2.36,4.37,0.41,0.41,0.41,0.41
1,LTHSC.34+.BM,0.71,1.64,0.10,0.10,0.10,1.64,0.10,0.71,0.10,...,13.37,2.57,10.26,7.41,8.79,8.79,7.41,0.71,1.64,0.71
2,STHSC.150-.BM,0.90,0.90,0.90,0.11,0.11,1.85,0.11,0.90,0.90,...,12.56,2.69,3.52,1.85,0.90,3.52,3.52,0.11,0.11,0.90
3,MPP4.135+.BM,0.11,0.83,0.11,0.11,0.11,1.58,0.11,0.11,0.11,...,11.37,2.58,2.15,3.49,2.15,2.58,3.04,0.83,0.83,3.49
4,proB.CLP.BM,1.94,0.47,0.47,0.79,0.47,1.12,0.11,1.57,0.42,...,20.08,4.58,2.89,5.76,3.25,4.21,6.46,0.90,0.90,2.85

# RNA-Seq transponierte Daten

In [8]:
RNA_Bcells = RNA.iloc[:, :23]
RNA_T_Bcells = RNA_Bcells.T
RNA_T_Bcells = RNA_T_Bcells.reset_index()
RNA_T_Bcells.to_csv("data/RNA_T_Bcells.csv", index=False)
RNA_T_Bcells.head()

,index,0,1,2,3,4,5,6,7,8,...,512585,512586,512587,512588,512589,512590,512591,512592,512593,512594
0,ImmGenATAC1219.peakID,ImmGenATAC1219.peak_1,ImmGenATAC1219.peak_2,ImmGenATAC1219.peak_3,ImmGenATAC1219.peak_4,ImmGenATAC1219.peak_5,ImmGenATAC1219.peak_6,ImmGenATAC1219.peak_7,ImmGenATAC1219.peak_8,ImmGenATAC1219.peak_9,...,ImmGenATAC1219.peak_512586,ImmGenATAC1219.peak_512587,ImmGenATAC1219.peak_512588,ImmGenATAC1219.peak_512589,ImmGenATAC1219.peak_512590,ImmGenATAC1219.peak_512591,ImmGenATAC1219.peak_512592,ImmGenATAC1219.peak_512593,ImmGenATAC1219.peak_512594,ImmGenATAC1219.peak_512595
1,chrom,chr1,chr1,chr1,chr1,chr1,chr1,chr1,chr1,chr1,...,chrY,chrY,chrY,chrY,chrY,chrY,chrY,chrY,chrY,chrY
2,Summit,3020786,3087226,3120109,3121485,3372787,3399217,3400115,3416260,3434092,...,90808861,90811022,90811406,90811728,90812084,90812450,90812906,90813175,90813624,90828985
3,mm10.60way.phastCons_scores,0.0,0.0,0.07,0.15,0.03,0.06,0.44,0.01,0.18,...,0.0,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,_-log10_bestPvalue,0.56,0.5,10.8,3.02,1.31,2.39,2.57,2.57,1.34,...,6.58,4.35,2.6,2.33,3.12,3.99,3.21,0.69,0.6,1.41